version: '2'

services:
    lychee:
        build: . 
        container_name: "lychee"
        environment:
            - VIRTUAL_HOST=lychee.lan
            - MYSQL_HOST=db
            - MYSQL_USER=root
            - MYSQL_PASSWORD=lalala
            - MYSQL_PREFIX=
        volumes:
            - ./data/uploads/:/var/www/Lychee/uploads
        ports:
            - "10880:80"

networks:
    default:
        external:
            name: proxied
